eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: I,You

---
spring:
  profiles: verb
words: ran,knew

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky

---
spring:
  profiles: noun
words: boat,book
